#!/bin/bash
# build.sh — assemble the standalone osascript tools from src/.
#
# AppleScript has no usable module system for scripts run via
# `osascript <file>`: a script cannot reliably locate a sibling library at
# run time (`path to me` resolves to osascript, not the script), and
# `osacompile` compiles one file without linking shared code. So the shared
# handlers live ONCE under src/lib/ and this script inlines them into each
# tool via `--#include <path-under-src>` directives, producing self-contained
# files at the repo root that users run directly with osascript.
#
# The generated files (forti.scpt, forti-disconnect.scpt, forti-status.scpt)
# are committed so the repo stays "clone and run"; CI and pre-commit rebuild
# with --check and fail if a committed file has drifted from src/.
#
# Usage:
#   ./build.sh            regenerate the tools at the repo root
#   ./build.sh --check    verify the committed tools match what src/ produces;
#                         exit 1 (with a diff) if any has drifted

set -euo pipefail

cd "$(dirname "$0")" || exit 1

# Source under src/<name>.applescript -> committed tool <name>.scpt
TOOLS=(forti forti-disconnect forti-status)

BANNER='-- GENERATED by build.sh — do not edit this file.
-- Edit src/<name>.applescript and the src/lib/*.applescript it includes,
-- then run ./build.sh. CI fails when a committed tool drifts from src/.'

# render <src-file>: print the shebang, the generated-file banner, then the
# body with every `--#include <path>` line replaced by the file it names.
render() {
	local src="$1" line inc first=1
	while IFS= read -r line || [ -n "$line" ]; do
		if [ "$first" -eq 1 ]; then
			printf '%s\n' "$line" # the shebang, kept as the first line
			printf '%s\n' "$BANNER"
			first=0
			continue
		fi
		case "$line" in
		'--#include '*)
			inc="src/${line#--#include }"
			[ -f "$inc" ] || {
				printf 'build.sh: missing include %s\n' "$inc" >&2
				exit 1
			}
			printf -- '-- ===== begin %s =====\n' "$inc"
			cat "$inc"
			printf -- '-- ===== end %s =====\n' "$inc"
			;;
		*) printf '%s\n' "$line" ;;
		esac
	done <"$src"
}

check=0
[ "${1:-}" = "--check" ] && check=1

rc=0
for t in "${TOOLS[@]}"; do
	src="src/$t.applescript"
	out="$t.scpt"
	[ -f "$src" ] || {
		printf 'build.sh: missing source %s\n' "$src" >&2
		exit 1
	}
	if [ "$check" -eq 1 ]; then
		if ! diff -u "$out" <(render "$src"); then
			printf 'build.sh: %s is out of sync with %s — run ./build.sh\n' "$out" "$src" >&2
			rc=1
		fi
	else
		render "$src" >"$out"
		printf 'built %s\n' "$out"
	fi
done

[ "$check" -eq 1 ] && [ "$rc" -eq 0 ] && printf 'build.sh: all tools in sync with src/\n'
exit "$rc"
